### ISSUE TITLE
Test authentication

### ISSUE THREAD

**Issue by romainreuillon** [openmole/openmole#106]
I would be nice to test each authentication in the authentication panel and indicate if it's working.

**Comment by mathieuleclaire** [comment]
Is there any method in the core, that could be called from the server, to achieve this ?

**Comment by romainreuillon** [comment]
Sort of... I think we could assemble some method call and exception catching to test it. I will first implement that in the matching core plugins.

**Comment by romainreuillon** [comment]
Test authentications has been enabled in the core.

**Comment by jopasserat** [comment]
This could help solve #1

**Comment by jopasserat** [comment]
Not sure what "Empty VO" means for a P12 certificate?

**Comment by mathieuleclaire** [comment]
It means you need to feed the VO settings with the name of the VO, which
matches with your authentication certificate. Otherwise no test are made
on the certificate. If you have a better warning string, do not hesitate !
Le 28/06/2016 19:27, jopasserat a écrit :
>
> Not sure what "Empty VO" means for a P12 certificate?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/openmole/openmole/issues/106#issuecomment-229120919>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAw1I2FNPJDrZFEIy5yOG63F-lhOyASWks5qQVmAgaJpZM4F6Eir>.
>


-- 
Ingénieur de Recherche ISCPIF-CNRS

Be green, keep it on the screen
Faites bonne impression et imprimez seulement au besoin!

**Comment by jopasserat** [comment]
it's just that i didn't see it initially :)
