### ISSUE TITLE
A way to guide/help the construction of new workflows by beginers ?

### ISSUE THREAD

**Issue by reyman** [openmole/openmole#131]
Hi all, 

A lot of efforts have been made by your team :) in the simplification of workflows DSL, and it's a great.

But, after some discussion with other users at geographie-cites, if it's easy to copy/paste and modify existing workflows like these already existing in open-mole market, it's still really hard to build custom workflows (from user says, it appear we can compare this pratice to some dangerous "off-trail" in ski activity ;) ? )

So, complexity is hidden, it's great, but in some ways we need to inform or guide users during workflow construction. Too much liberty is too much, users don't know what keyword they can use or not use in context. 

For example it's hard to know for an user if i need to add parenthesis or not when i call `env` on a task : `(gama on env)` or `gama on env`  ? What can i do if `strainer()` don't work in my case ? Is it a puzzle workflow or not when i write this combination of task ? etc. And Scala doc is very hard to read for beginner.

Perhaps, it lacks some basic rule dictionnary (after this keyword, you can do this, and this, and etc.), or some completions, or some feedback, or interactive documentation in the code windows to guide the construction for beginners.

My idea is not to critic the DSL, but to highlight how we can resolve some frustratiosn expressed by "non computer scientist" users. We can also talk together about that with a coffee at isc-pif :)

**Comment by romainreuillon** [comment]
Agreed that we should smooth the learning curve has much as possible. To achieve that, I think we should identify some blocking point and overcome them one at a time. For the 2 points mentioned in your issue I would say:
- the strainer: it is actually a workflow puzzle, being able to visualise the complete generated workflow once it is compiled would be a good way to solve that, so the user can visualise what it's generated workflow looks like and diagnose the pb,
- the on, by... keywords: the problem is operator priority. I think we should develop a scala compiler plugin that would add those parenthesis automatically in the syntax tree. I am not sure how the scala compilation phases work but I would be glad to look into it with you to see if we can come up with a working solution. It might not be that hard consedering that there already is a whole scala plugin ecosystem, we can have a look at. This would be a huge improvement in the dsl. It also concerns the samplings where you have to add lots of parenthesis to specify the priority even if it is unambiguous and should be handled by the compiler.

It is great to see that the user community starts to love and hate some OpenMOLE aspects. We should definitely list those frustrations and take them into account in our development decisions.

**Comment by jopasserat** [comment]
If it's fine with you guys, I'd like to move this very interesting discussion to the user mailing list.

I think it's time to get more users involved at least to get some feedback of the documentation or to propose tutorials as Guillaume (Cherel) has done in the market (awesomely comprehensive and detailed tutorial about advanced netlogo model exploration).

**Comment by reyman** [comment]
Hi,
No problem for me to continue the discussion on mailling list.
On my side, i try to motivate users at geographie cité lab to participate more actively (by idea or critics) to this interesting discussion.
