### ISSUE TITLE
Make sure a file is fully loaded before saving it

### ISSUE THREAD

**Issue by romainreuillon** [openmole/openmole#134]
Due to a network latency a file was not loaded in the editor and OpenMOLE erased it by saving it as an empty file on close.

**Comment by romainreuillon** [comment]
Launch auto only after load.

**Comment by mathieuleclaire** [comment]
Not reproduced yet. Moved to Milestone 7 to keep an eye on it.

**Comment by jopasserat** [comment]
I think I've just experienced the same behaviour in the dev branch.
It can be easily reproduced with the debug mode now (run `openmole --debug` and create a new Remote debugging session in IntelliJ).

Because the debugger stops the application, it prevents the app from behaving normally and mimics the networks  latency.

I've seen the "couldn't save file" message a couple of times with no harm but now my file has been wiped out.
