### ISSUE TITLE
.tmp directories not cleaned anymore??

### ISSUE THREAD

**Issue by jopasserat** [openmole/openmole#193]
Rob reported that his .tmp are never cleaned (both ~/.openmole/.tmp and ~/.openmole/hostname/.tmp).
I noticed I also have some fairly old directories myself (some dating back from 2 years while I thought they were cleaned if not used after 30 days).

I think this piece of code is not called: https://github.com/openmole/openmole/blob/master/openmole/core/org.openmole.core.workspace/src/main/scala/org/openmole/core/workspace/Workspace.scala#L64-L68

Could it be that the mechanism doesn't work with the WebUI?

**Comment by romainreuillon** [comment]
The 30 days cleaning it for remote files only.

Could you provide a reproducible case where the local files are not cleaned despite they should have been?

**Comment by jopasserat** [comment]
can't find one at the moment, could be that my trailing directories where the result of previous crashes..
let's see if Rob comes up with something

**Comment by physrr** [comment]
Hey, I *think* I've managed to put together a small version of the project I've been working on. If you clone this to your openmole "projects" folder and run "runRCAexample.oms": https://github.com/physrr/RCAexample

When I have crashes in openmole, or where I've had to force-quit due to a dropped network connection, I have to manually delete the ./.openmole/.tmp directory in order to re-open openmole. Additionally, it seems like a new folder is created in ./.openmole/.tmp each day that I use the application.

**Comment by romainreuillon** [comment]
I think we might find a generic cleaning algorithm:

It would be possible to lock a file in the ./tmp/uuid/ directory for each running openmole instance (if several).  On startup we clean all tmp dirs with no lock (meaning unused tmp dir). Would it solve the issue?

**Comment by jopasserat** [comment]
very likely fixed by 	62886e2-7e9e9cd
@physrr if you can give it a shot when you've got time (no hurry)
