### ISSUE TITLE
Labels don't disappear

### ISSUE THREAD

**Issue by romainreuillon** [openmole/openmole#205]
![image](https://cloud.githubusercontent.com/assets/1270995/25063573/288a76fc-21e8-11e7-8733-218c486e7371.png)

Sometimes labels don't disappear and I make the underneath folder unreachable.

**Comment by mathieuleclaire** [comment]
Tooltips are not easy to deal with in the file browser because it is refreshed all the time and the tooltips have to be killed manually it that time. Tooltips are thought for a static use. So I removed those tooltip for now but the long name won't be precised any more. We could imagine an other way to precise the full name for a given file.

**Comment by mathieuleclaire** [comment]
A new way of triggering actions fixes this after commit a68b3e15ebd1552390d294440a604818f6d67857
![title](https://user-images.githubusercontent.com/800035/37358671-f5dc898e-26eb-11e8-9359-1b33478d32ed.png)
