### ISSUE TITLE
[GUI] Code highlighting does not work

### ISSUE THREAD

**Issue by JusteRaimbault** [openmole/openmole#347]
I know it has already been discussed but couldn't find the related issue ; code highlighting in the gui does not work for me (Firefox 60.0.2 on Ubuntu 18.04), is there an easy way to fix that ?

**Comment by mathieuleclaire** [comment]
I think it is due to the way you build OpenMOLE. Do you use the buildOpenMOLE sbt key ?

**Comment by JusteRaimbault** [comment]
yes I use it ; is there a specific key for building the gui correctly or does buildOpenMOLE do the job ?

**Comment by mathieuleclaire** [comment]
Yes. @jopasserat. Do you still have this problem ?

**Comment by JusteRaimbault** [comment]
seems not directly related to the browser used, it does not work either with Google chrome (which I just installed for testing)

**Comment by mathieuleclaire** [comment]
Yes, it is what we observed at the CC. Neither the distribution. I think it is more about the way we construct openMOLE.

**Comment by JusteRaimbault** [comment]
Any update on that ?
(by the way the highlighting works on mac, shame on ubuntu ;) :octocat: :octocat: )

**Comment by mathieuleclaire** [comment]
The problem is that I can't reproduce the problem. Can you confirm me that OpenMOLE tries to download a js file when a .oms file is opened and fails to do it (switch to debug mode / network)?

**Comment by kzollman** [comment]
I know that this issue is closed, but it appears to be because you could not reproduce it.  (Let me know if you would prefer I open a new issue.) I am having the same problem: no syntax highlighting.  Here's my system information:

OS: Ubuntu 18.04 (64-bit)
Browsers: both Chromium (71.0.3578.98) and Firefox (65.0)
Java: both Oracle Java 8 and OpenJDK 11 

No obvious errors are being printed on the terminal.  Please let me know what additional information I could provide that would be useful.

If it is helpful, I have attached a screenshot.
![screenshot from 2019-02-05 20-47-10](https://user-images.githubusercontent.com/18035057/52315948-436c3700-2987-11e9-9227-4a331176f961.png)

**Comment by mathieuleclaire** [comment]
Hi,
well, I never suceeded in reproducing this bug on my computer but it occurs time to time.
how did you obtain the OpenMOLE application (archive download or source code compiilation)? Did you test on Firefox ?
Mathieu

**Comment by kzollman** [comment]
Yeah, it happened on both Chromium and Firefox and has been consistent over five or so uses.  The installation is from the downloaded tarball.   If I have some time this afternoon, I can download the source and compile it.  When I have a chance, I'll report back on the results. 

Let me know what tests you'd like me to perform, I'd be happy to do whatever can help.

**Comment by kzollman** [comment]
I compiled from source and even then there is no highlighting.
