### ISSUE TITLE
Migrate NetlogoTask to singularity

### ISSUE THREAD

**Issue by romainreuillon** [openmole/openmole#484]
Netologo is having performance and memory issue when called through the java API. Migrating it to a container will fix these pb, and have other advantages such as a better decoupling. User can test their code using the netlogo headless and expect the same behavior in openmole.

**Comment by JusteRaimbault** [comment]
This is strange, I use NetLogo a lot and never observed any significant discrepancy between headless time and OpenMOLE time - but I run small models. Do you have a minimal working example where the difference is significant? (I don't get why it should be, calling the headless API is from what I thought exactly the same as running the headless).

I wouldn't be in favour of a switch - what's useful in the current NetLogo task is that we can have elaborated types (nested arrays), we can run commands easily, etc. - there is a stronger integration than with a container. If the issue is on a very specific case I would suggest to use a ContainerTask and keep the API for the NetLogo task.

**Comment by romainreuillon** [comment]
Hi @JusteRaimbault,
I think we could have an integration with Netlogo which is just as good even using a container version. What worries me is the compilation time of the netlogo model by netlogo (which wouldn't be cached anymore) that could lead to significant overhead....
Here is the model that run in 2s in the headless and in 50s in OpenMOLE. This is really wierd and I don't know how to investigate.

[AEDESS.zip](https://github.com/openmole/openmole/files/5188819/AEDESS.zip)

cheers, Romain

**Comment by JusteRaimbault** [comment]
Thanks for the example!
I agree for the full integration (the way we use commands is as a single block so it would be the same) except for the nested arrays - the R Task does not have them for example. Maybe also File type (I think it is handled directly?). But we could handle nested arrays with a communication json file as in other containers I guess?

For the runtime issue it seems linked to the number of agents - but not the memory footprint (I run models with very few agents / interactions between them, but sometimes large matrices and never had the issue)? (in that case it is enormous!)
One way to check if it is a bug of NetLogo or a bug of OpenMOLE would be to run it through the API but not from OpenMOLE (I did that back in the days when investigating the issue with extension jars never closed) - I could try this soon when I find time.

**Comment by JusteRaimbault** [comment]
(one additional more philosophical thought: if we move everything to singularity, will OpenMOLE become just a GUI for Singularity? :'( )(joking, I'm not forgetting the methods and environments!)

**Comment by romainreuillon** [comment]
You're right, I'll first work on nested array with arbitrary levels for the R task. This should be fast.

That benchmark using the API would be very useful, @helenea tested it using the netlogo-headless.sh but this headless does something that OpenMOLE does'nt using the Netlogo API and it makes the model execution very fast.

From the philosophical perspective: untying the simulation platform from OpenMOLE is a good thing on many aspects:
 - it makes it easier for the use to manually run some OpenMOLE experiments to check what is happening, 
 - it make OpenMOLE less sensitive to memory leaks of these plateform,
 - it shrinks the size of OpenMOLE
 - it make the bug repports to the platform devs a lot more easy.

OpenMOLE add way more value than running singularity or distributing the computation. Singularity could be viewed as a building block of OpenMOLE as the JVM or the Scala compiler are building blocks as well.

**Comment by JusteRaimbault** [comment]
I did not realize there was so much aspects of unifying tasks with Singularity - then I totally agree with the switch if complicated types can be kept.

**Comment by romainreuillon** [comment]
For the complicated types, we should be studying what are the capacities of the netlogo headless to this regard. Do you have any experience to that regard ?

**Comment by JusteRaimbault** [comment]
You mean serialization capabilities? The only built-in primitive is `export-world` but I think it would be quite dirty to go get the serialized globals into it (which is plain text from what I could remember but literally everything is in it). I know a json extension but only for reading, not writing; there may be other serialization extensions out there, I need to have a look. Otherwise I can quickly write one that exactly fits what we want to do.
If I understood well, the idea would to have output prototypes in a json file, which is then read as in the R task?

**Comment by romainreuillon** [comment]
Hi @JusteRaimbault,

I am not sure yet how we will get the outputs. I am looking into the csv output by the netlogo headless to see what are the limits. If it is too limitating, we could use an external plugin.

Before that, I am working on generifying the code to handle multiple levels of array, in order to make it recuse on json and other potential output format provided we implement the right parser.

Romain

**Comment by romainreuillon** [comment]
I just generified the multidimensional array extraction: 64a9f5767f54b22531ee5d685156bb136d8e3660

 The RTask is now able to output N dimension array... I'm going to work on NetLogo containerisation now.

**Comment by romainreuillon** [comment]
A showstopper for the containerization of netlogo task. The netlogo headless doesn't exit on error, it just hangs. This is a blocking bug for the OpenMOLE integration.

**Comment by JusteRaimbault** [comment]
Damn, that's a weird behavior! Could using the headless API from a simple java app like we did here: https://github.com/NetLogo/NetLogo/issues/909 be a solution? Or would there still be the performance issues that seem to be due to the use of the API? I guess we need to have the results of the benchmark mentioned above to know if this is a possible option.

**Comment by romainreuillon** [comment]
Yes this might be a solution indeed. I'll try that next week to benchmark Helene's model using this.

**Comment by romainreuillon** [comment]
@JusteRaimbault Do you have a scala project setup to run this ?

**Comment by JusteRaimbault** [comment]
It is here: https://github.com/JusteRaimbault/CityNetwork/tree/master/Models/Misc/OpenMole/TestOpenFiles/bugnetlogo
but with NetLogo 5.2 and sorry it is not in a standalone repo (and has mess committed, target, classes) - you actually just need `assets`, `lib`, `src` and `build.sbt`

**Comment by reyman** [comment]
I think we need to decorrelate task with container and task without. 

I know / I'm aggre that "containerization" is a good choice for future, but actually not all HPC/meso-centre cluster support it. 
We need to preserve some retrocompatibility for these users (like me).

**Comment by romainreuillon** [comment]
Implemented here: https://gitlab.openmole.org/openmole/openmole/-/blob/dev/openmole/plugins/org.openmole.plugin.task.netlogo/src/main/scala/org/openmole/plugin/task/netlogo/NetLogoContainerTask.scala
